import PDFDocument from 'pdfkit';
import { getColors, addPageHeader, addSection, addFooter } from '../utils/pdfStyles.js';

const PDF_STRINGS = {
  en: {
    title: 'Assessment Report - Trajetória',
    subject: 'Complete Assessment Report',
    coverSubtitle: 'Complete Assessment Report',
    name: 'Name',
    age: 'Age',
    location: 'Location',
    email: 'Email',
    reportDate: 'Report Date',
    coverDesc: 'This report presents a complete analysis of your results across multiple self-awareness and career orientation assessments. The data here is based on your answers and aims to support your personal and professional development.',
    toc: 'Table of Contents',
    tocItems: [
      { title: '1. Initial Anamnesis', page: 3 },
      { title: '2. DISC Insight - Personality Profile', key: 'disc-insight' },
      { title: '3. Multiple Intelligences', key: 'multiple-intelligences' },
      { title: '4. RIASEC - Career Orientation', key: 'riasec' },
      { title: '5. Personality Archetypes', key: 'archetypes' },
      { title: '6. Conclusions and Recommendations', page: 'last' },
    ],
    notCompleted: '(not completed)',
    initialAnamnesis: 'Initial Anamnesis',
    personalInfo: 'Personal Information',
    education: 'Education',
    studyArea: 'Study Area',
    professionalSituation: 'Professional Situation',
    currentOccupation: 'Current Occupation',
    areasOfInterest: 'Areas of Interest',
    careerGoals: 'Career Goals',
    completedOn: 'Completed on',
    yourDiscProfile: 'Your DISC Profile',
    dominantProfile: 'Dominant Profile',
    fullDistribution: 'Full Distribution',
    discTypes: [
      { key: 'D', name: 'Dominance', description: 'Results-oriented, direct and decisive' },
      { key: 'I', name: 'Influence', description: 'Sociable, persuasive and optimistic' },
      { key: 'S', name: 'Steadiness', description: 'Stable, patient and loyal' },
      { key: 'C', name: 'Conscientiousness', description: 'Accurate, analytical and systematic' },
    ],
    top3Intelligences: 'Your Top 3 Dominant Intelligences',
    fullProfile: 'Full Profile',
    miTypes: [
      { key: 'espacial', name: 'Spatial', description: 'Spatial visualization and manipulation' },
      { key: 'logica', name: 'Logical-Mathematical', description: 'Logical and mathematical reasoning' },
      { key: 'linguistica', name: 'Linguistic', description: 'Written and spoken language' },
      { key: 'musical', name: 'Musical', description: 'Music perception and creation' },
      { key: 'corporal', name: 'Bodily-Kinesthetic', description: 'Physical and motor skills' },
      { key: 'interpessoal', name: 'Interpersonal', description: 'Interaction with others' },
      { key: 'intrapessoal', name: 'Intrapersonal', description: 'Self-knowledge and reflection' },
      { key: 'naturalista', name: 'Naturalist', description: 'Connection with nature' },
    ],
    idealCareers: 'Ideal Careers',
    hollandCodeTop3: 'Your Holland Code (Top 3)',
    allProfiles: 'All Profiles',
    riasecProfiles: [
      { key: 'R', name: 'Realistic', description: 'Prefers hands-on, practical activities.', careers: 'Engineering, mechanics, agriculture, construction, veterinary' },
      { key: 'I', name: 'Investigative', description: 'Analytical, enjoys solving complex problems.', careers: 'Science, medicine, research, data analysis, technology' },
      { key: 'A', name: 'Artistic', description: 'Creative, values personal expression.', careers: 'Design, arts, music, literature, architecture, advertising' },
      { key: 'S', name: 'Social', description: 'Enjoys working with people and helping others.', careers: 'Education, psychology, social work, HR, nursing' },
      { key: 'E', name: 'Enterprising', description: 'Persuasive, enjoys leading.', careers: 'Management, sales, marketing, law, entrepreneurship' },
      { key: 'C', name: 'Conventional', description: 'Organized, values precision and efficiency.', careers: 'Accounting, administration, finance, secretarial' },
    ],
    yourDominantArchetypes: 'Your Dominant Archetypes',
    conclusions: 'Conclusions and Recommendations',
    summaryOfTests: 'Summary of Completed Tests',
    testsCompletedCount: 'You have completed {{count}} self-awareness and career orientation assessment(s).',
    mentorFinalMessage: "Mentor's Final Message",
    nextSteps: 'Next Steps',
    recommendations: [
      'Review your results regularly to track your progress',
      'Use the information to guide your career decisions',
      'Seek opportunities that align with your strengths',
      'Consider developing areas you wish to strengthen',
      'Share your results with mentors or career coaches',
    ],
    reportGeneratedBy: 'This report was automatically generated by the Trajetória platform.',
    generationDate: 'Generation date',
    lifePlan: 'Personalized Life Plan',
    vision: 'Overview',
    developmentPhases: 'Development Phases',
    phase: 'Phase',
    habitsAndSupport: 'Habits and Support Routines',
    supportNetwork: 'Support Network and Resources',
    vocationalReport: 'Complete Vocational Report',
  },
  pt: {
    title: 'Relatório de Testes - Trajetória',
    subject: 'Relatório Completo de Avaliações',
    coverSubtitle: 'Relatório Completo de Avaliações',
    name: 'Nome',
    age: 'Idade',
    location: 'Localização',
    email: 'E-mail',
    reportDate: 'Data do Relatório',
    coverDesc: 'Este relatório apresenta uma análise completa dos seus resultados em múltiplos testes de autoconhecimento e orientação profissional. Os dados aqui apresentados são baseados nas suas respostas e têm como objetivo auxiliar no seu desenvolvimento pessoal e profissional.',
    toc: 'Sumário',
    tocItems: [
      { title: '1. Anamnese Inicial', page: 3 },
      { title: '2. DISC Insight - Perfil de Personalidade', key: 'disc-insight' },
      { title: '3. Inteligências Múltiplas', key: 'multiple-intelligences' },
      { title: '4. RIASEC - Orientação Profissional', key: 'riasec' },
      { title: '5. Arquétipos de Personalidade', key: 'archetypes' },
      { title: '6. Conclusões e Recomendações', page: 'última' },
    ],
    notCompleted: '(não realizado)',
    initialAnamnesis: 'Anamnese Inicial',
    personalInfo: 'Informações Pessoais',
    education: 'Escolaridade',
    studyArea: 'Área de Estudo',
    professionalSituation: 'Situação Profissional',
    currentOccupation: 'Ocupação Atual',
    areasOfInterest: 'Áreas de Interesse',
    careerGoals: 'Objetivos de Carreira',
    completedOn: 'Realizado em',
    yourDiscProfile: 'Seu Perfil DISC',
    dominantProfile: 'Perfil Dominante',
    fullDistribution: 'Distribuição Completa',
    discTypes: [
      { key: 'D', name: 'Dominância', description: 'Orientado para resultados, direto e decidido' },
      { key: 'I', name: 'Influência', description: 'Sociável, persuasivo e otimista' },
      { key: 'S', name: 'Estabilidade', description: 'Estável, paciente e leal' },
      { key: 'C', name: 'Conformidade', description: 'Preciso, analítico e sistemático' },
    ],
    top3Intelligences: 'Suas 3 Inteligências Dominantes',
    fullProfile: 'Perfil Completo',
    miTypes: [
      { key: 'espacial', name: 'Espacial', description: 'Visualização e manipulação espacial' },
      { key: 'logica', name: 'Lógico-Matemática', description: 'Raciocínio lógico e matemático' },
      { key: 'linguistica', name: 'Linguística', description: 'Linguagem escrita e falada' },
      { key: 'musical', name: 'Musical', description: 'Percepção e criação musical' },
      { key: 'corporal', name: 'Corporal-Cinestésica', description: 'Habilidades físicas e motoras' },
      { key: 'interpessoal', name: 'Interpessoal', description: 'Interação com outras pessoas' },
      { key: 'intrapessoal', name: 'Intrapessoal', description: 'Autoconhecimento e reflexão' },
      { key: 'naturalista', name: 'Naturalista', description: 'Conexão com a natureza' },
    ],
    idealCareers: 'Carreiras Ideais',
    hollandCodeTop3: 'Seu Código Holland (Top 3)',
    allProfiles: 'Todos os Perfis',
    riasecProfiles: [
      { key: 'R', name: 'Realista', description: 'Prefere atividades práticas e trabalho manual.', careers: 'Engenharia, mecânica, agricultura, construção, veterinária' },
      { key: 'I', name: 'Investigativo', description: 'Analítico, gosta de resolver problemas complexos.', careers: 'Ciências, medicina, pesquisa, análise de dados, tecnologia' },
      { key: 'A', name: 'Artístico', description: 'Criativo, valoriza a expressão pessoal.', careers: 'Design, artes, música, literatura, arquitetura, publicidade' },
      { key: 'S', name: 'Social', description: 'Gosta de trabalhar com pessoas e ajudar os outros.', careers: 'Educação, psicologia, serviço social, RH, enfermagem' },
      { key: 'E', name: 'Empreendedor', description: 'Persuasivo, gosta de liderar.', careers: 'Administração, vendas, marketing, direito, empreendedorismo' },
      { key: 'C', name: 'Convencional', description: 'Organizado, valoriza precisão e eficiência.', careers: 'Contabilidade, administração, finanças, secretariado' },
    ],
    yourDominantArchetypes: 'Seus Arquétipos Dominantes',
    conclusions: 'Conclusões e Recomendações',
    summaryOfTests: 'Resumo dos Testes Realizados',
    testsCompletedCount: 'Você completou {{count}} teste(s) de autoconhecimento e orientação profissional.',
    mentorFinalMessage: 'Mensagem Final do Mentor',
    nextSteps: 'Próximos Passos',
    recommendations: [
      'Revise seus resultados regularmente para acompanhar sua evolução',
      'Utilize as informações para guiar suas decisões de carreira',
      'Busque oportunidades que alinhem com seus pontos fortes',
      'Considere desenvolver áreas que deseja fortalecer',
      'Compartilhe seus resultados com mentores ou coaches de carreira',
    ],
    reportGeneratedBy: 'Este relatório foi gerado automaticamente pela plataforma Trajetória.',
    generationDate: 'Data de geração',
    lifePlan: 'Plano de Vida Personalizado',
    vision: 'Visão Geral',
    developmentPhases: 'Fases de Desenvolvimento',
    phase: 'Fase',
    habitsAndSupport: 'Hábitos e Rotinas de Suporte',
    supportNetwork: 'Rede de Apoio e Recursos',
    vocationalReport: 'Relatório Vocacional Completo',
  },
};

function getStrings(lang) {
  return PDF_STRINGS[lang === 'en' ? 'en' : 'pt'] || PDF_STRINGS.en;
}

/**
 * Gera um PDF completo com todos os resultados dos testes
 * @param {string} lang - 'en' or 'pt'
 */
export async function generateCompletePDF(userData, tests, roadmap, completeNarrative = null, lang = 'en') {
  const s = getStrings(lang);
  const locale = lang === 'en' ? 'en-US' : 'pt-BR';

  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ 
        size: 'A4',
        margins: { top: 60, bottom: 60, left: 50, right: 50 },
        info: {
          Title: s.title,
          Author: 'Trajetória Platform',
          Subject: s.subject
        }
      });

      const buffers = [];
      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', () => {
        const pdfBuffer = Buffer.concat(buffers);
        resolve(pdfBuffer);
      });
      doc.on('error', reject);

      const colors = getColors();

      addCoverPage(doc, userData, colors, s, locale);
      doc.addPage();
      addTableOfContents(doc, tests, colors, s);
      doc.addPage();
      addPageHeader(doc, s.initialAnamnesis, colors);
      addAnamneseSection(doc, userData, colors, s);

      if (tests['disc-insight']) {
        doc.addPage();
        addPageHeader(doc, s.tocItems[1].title, colors);
        addDISCSection(doc, tests['disc-insight'], colors, s, locale);
      }

      if (tests['multiple-intelligences']) {
        doc.addPage();
        addPageHeader(doc, s.tocItems[2].title, colors);
        addMultipleIntelligencesSection(doc, tests['multiple-intelligences'], colors, s, locale);
      }

      if (tests['riasec']) {
        doc.addPage();
        addPageHeader(doc, s.tocItems[3].title, colors);
        addRIASECSection(doc, tests['riasec'], colors, s, locale);
      }

      if (tests['archetypes']) {
        doc.addPage();
        addPageHeader(doc, s.tocItems[4].title, colors);
        addArchetypesSection(doc, tests['archetypes'], colors, s, locale);
      }

      if (roadmap) {
        doc.addPage();
        addPageHeader(doc, s.lifePlan, colors);
        addRoadmapSection(doc, roadmap, colors, s);
      }

      if (completeNarrative) {
        doc.addPage();
        addPageHeader(doc, s.vocationalReport, colors);
        addCompleteNarrativeSection(doc, completeNarrative, colors);
      }

      doc.addPage();
      addConclusionPage(doc, userData, tests, colors, roadmap, s, locale);

      doc.end();

    } catch (error) {
      reject(error);
    }
  });
}

// ============ FUNÇÕES AUXILIARES ============

function addCoverPage(doc, userData, colors, s, locale = 'en-US') {
  doc.fontSize(36)
     .fillColor(colors.primary)
     .text('TRAJETÓRIA', { align: 'center' });

  doc.moveDown(0.5);
  doc.fontSize(18)
     .fillColor(colors.secondary)
     .text(s.coverSubtitle, { align: 'center' });

  doc.moveDown(3);

  const boxY = doc.y;
  doc.roundedRect(50, boxY, doc.page.width - 100, 180, 10)
     .fillAndStroke(colors.lightBackground, colors.primary);

  const notInformed = locale.startsWith('en') ? 'Not provided' : 'Não informado';
  const notInformedF = locale.startsWith('en') ? 'Not provided' : 'Não informada';
  doc.fillColor(colors.text)
     .fontSize(14)
     .text(`${s.name}: ${userData.nomeCompleto || notInformed}`, 70, boxY + 30);
  doc.text(`${s.age}: ${userData.idade || notInformedF}`, 70, boxY + 60);
  doc.text(`${s.location}: ${userData.cidadeEstado || notInformedF}`, 70, boxY + 90);
  doc.text(`${s.email}: ${userData.email || notInformed}`, 70, boxY + 120);
  doc.text(`${s.reportDate}: ${new Date().toLocaleDateString(locale)}`, 70, boxY + 150);

  doc.moveDown(8);
  doc.fontSize(11)
     .fillColor(colors.textLight)
     .text(s.coverDesc, { align: 'justify', lineGap: 5 });
}

function addTableOfContents(doc, tests, colors, s) {
  doc.fontSize(24)
     .fillColor(colors.primary)
     .text(s.toc, { underline: true });

  doc.moveDown(2);

  doc.fontSize(12);
  s.tocItems.forEach((item) => {
    const included = item.key ? !!tests[item.key] : true;
    if (item.key && !included) {
      doc.fillColor(colors.textLight)
         .text(`${item.title} ${s.notCompleted}`, { continued: false });
    } else {
      doc.fillColor(colors.text)
         .text(item.title, { continued: false });
    }
    doc.moveDown(0.8);
  });
}

function addAnamneseSection(doc, userData, colors, s) {
  addSection(doc, s.personalInfo, colors);

  doc.fontSize(11)
     .fillColor(colors.text)
     .text(`${s.name}: ${userData.nomeCompleto || 'N/A'}`)
     .moveDown(0.5)
     .text(`${s.age}: ${userData.idade || 'N/A'}`)
     .moveDown(0.5)
     .text(`${s.location}: ${userData.cidadeEstado || 'N/A'}`)
     .moveDown(0.5)
     .text(`${s.email}: ${userData.email || 'N/A'}`)
     .moveDown(1.5);

  if (userData.nivelEscolaridade) {
    addSection(doc, s.education, colors);
    doc.fontSize(11)
       .fillColor(colors.text)
       .text(userData.nivelEscolaridade);
    if (userData.areaEstudo) {
      doc.moveDown(0.5).text(`${s.studyArea}: ${userData.areaEstudo}`);
    }
    doc.moveDown(1.5);
  }

  if (userData.situacaoProfissional) {
    addSection(doc, s.professionalSituation, colors);
    doc.fontSize(11)
       .fillColor(colors.text)
       .text(userData.situacaoProfissional);
    if (userData.ocupacaoAtual) {
      doc.moveDown(0.5).text(`${s.currentOccupation}: ${userData.ocupacaoAtual}`);
    }
    doc.moveDown(1.5);
  }

  if (userData.areasInteresse && userData.areasInteresse.length > 0) {
    addSection(doc, s.areasOfInterest, colors);
    doc.fontSize(11)
       .fillColor(colors.text)
       .list(userData.areasInteresse, { bulletRadius: 2 });
    doc.moveDown(1.5);
  }

  if (userData.objetivosCarreira && userData.objetivosCarreira.length > 0) {
    addSection(doc, s.careerGoals, colors);
    doc.fontSize(11)
       .fillColor(colors.text)
       .list(userData.objetivosCarreira, { bulletRadius: 2 });
  }
}

function addDISCSection(doc, testData, colors, s, locale = 'en-US') {
  const { results, completedAt } = testData;
  doc.fontSize(10)
     .fillColor(colors.textLight)
     .text(`${s.completedOn}: ${new Date(completedAt).toLocaleDateString(locale)}`)
     .moveDown(2);

  addSection(doc, s.yourDiscProfile, colors);
  const types = s.discTypes;
  const dominant = Object.entries(results).reduce((a, b) => a[1] > b[1] ? a : b);
  const dominantType = types.find(t => t.key === dominant[0]);

  doc.fontSize(14)
     .fillColor(colors.primary)
     .text(`${s.dominantProfile}: ${dominantType.name} (${dominant[1]}%)`, { underline: true })
     .moveDown(1);
  doc.fontSize(11)
     .fillColor(colors.text)
     .text(dominantType.description)
     .moveDown(2);

  addSection(doc, s.fullDistribution, colors);
  types.forEach(type => {
    const percentage = results[type.key];
    doc.fontSize(11)
       .fillColor(colors.text)
       .text(`${type.name} (${type.key}): ${percentage}%`);
    const barWidth = (percentage / 100) * 400;
    const yPos = doc.y + 5;
    doc.rect(doc.x, yPos, 400, 10)
       .fillAndStroke(colors.lightBackground, colors.border);
    doc.rect(doc.x, yPos, barWidth, 10)
       .fill(colors.primary);
    doc.moveDown(1.5);
  });
}

function addMultipleIntelligencesSection(doc, testData, colors, s, locale = 'en-US') {
  const { results, completedAt } = testData;
  doc.fontSize(10)
     .fillColor(colors.textLight)
     .text(`${s.completedOn}: ${new Date(completedAt).toLocaleDateString(locale)}`)
     .moveDown(2);

  const intelligences = s.miTypes;
  const sorted = Object.entries(results).sort((a, b) => b[1] - a[1]);
  const top3 = sorted.slice(0, 3);

  addSection(doc, s.top3Intelligences, colors);
  top3.forEach(([key, value], index) => {
    const intelligence = intelligences.find(i => i.key === key);
    const ord = locale.startsWith('en') ? `${index + 1}.` : `${index + 1}º`;
    doc.fontSize(12)
       .fillColor(colors.primary)
       .text(`${ord} ${intelligence.name}: ${value}%`, { underline: true })
       .moveDown(0.5);
    doc.fontSize(10)
       .fillColor(colors.text)
       .text(intelligence.description)
       .moveDown(1.5);
  });

  addSection(doc, s.fullProfile, colors);
  intelligences.forEach(intelligence => {
    const percentage = results[intelligence.key];
    doc.fontSize(11)
       .fillColor(colors.text)
       .text(`${intelligence.name}: ${percentage}%`);
    const barWidth = (percentage / 100) * 400;
    const yPos = doc.y + 5;
    doc.rect(doc.x, yPos, 400, 10)
       .fillAndStroke(colors.lightBackground, colors.border);
    doc.rect(doc.x, yPos, barWidth, 10)
       .fill(colors.secondary);
    doc.moveDown(1.5);
  });
}

function addRIASECSection(doc, testData, colors, s, locale = 'en-US') {
  const { results, completedAt } = testData;
  doc.fontSize(10)
     .fillColor(colors.textLight)
     .text(`${s.completedOn}: ${new Date(completedAt).toLocaleDateString(locale)}`)
     .moveDown(2);

  const profiles = s.riasecProfiles;
  const sorted = Object.entries(results).sort((a, b) => b[1] - a[1]);
  const dominantKey = sorted[0][0];
  const dominantProfile = profiles.find(p => p.key === dominantKey);

  addSection(doc, `${s.dominantProfile}: ${dominantProfile.name}`, colors);
  doc.fontSize(11)
     .fillColor(colors.text)
     .text(dominantProfile.description)
     .moveDown(1);
  doc.fontSize(10)
     .fillColor(colors.primary)
     .text(`${s.idealCareers}:`, { underline: true })
     .moveDown(0.5);
  doc.fontSize(10)
     .fillColor(colors.text)
     .text(dominantProfile.careers)
     .moveDown(2);

  addSection(doc, s.hollandCodeTop3, colors);
  sorted.slice(0, 3).forEach(([key, value]) => {
    const profile = profiles.find(p => p.key === key);
    doc.fontSize(11)
       .fillColor(colors.primary)
       .text(`${key} - ${profile.name}: ${value}%`)
       .moveDown(0.3);
  });
  doc.moveDown(2);

  addSection(doc, s.allProfiles, colors);
  profiles.forEach(profile => {
    const percentage = results[profile.key];
    doc.fontSize(11)
       .fillColor(colors.text)
       .text(`${profile.name} (${profile.key}): ${percentage}%`);
    const barWidth = (percentage / 100) * 400;
    const yPos = doc.y + 5;
    doc.rect(doc.x, yPos, 400, 10)
       .fillAndStroke(colors.lightBackground, colors.border);
    doc.rect(doc.x, yPos, barWidth, 10)
       .fill(colors.primary);
    doc.moveDown(1.5);
  });
}

const ARCHETYPE_NAMES = {
  en: { inocente: 'Innocent', sabio: 'Sage', explorador: 'Explorer', foraDaLei: 'Outlaw', mago: 'Magician', heroi: 'Hero', amante: 'Lover', bobo: 'Jester', caraComum: 'Everyman', cuidador: 'Caregiver', governante: 'Ruler', criador: 'Creator' },
  pt: { inocente: 'Inocente', sabio: 'Sábio', explorador: 'Explorador', foraDaLei: 'Fora da Lei', mago: 'Mago', heroi: 'Herói', amante: 'Amante', bobo: 'Bobo', caraComum: 'Cara Comum', cuidador: 'Cuidador', governante: 'Governante', criador: 'Criador' },
};

function addArchetypesSection(doc, testData, colors, s, locale = 'en-US') {
  const { results, completedAt } = testData;
  doc.fontSize(10)
     .fillColor(colors.textLight)
     .text(`${s.completedOn}: ${new Date(completedAt).toLocaleDateString(locale)}`)
     .moveDown(2);

  addSection(doc, s.yourDominantArchetypes, colors);
  if (results && typeof results === 'object') {
    const lang = s.toc === 'Sumário' ? 'pt' : 'en';
    const names = ARCHETYPE_NAMES[lang];
    const sorted = Object.entries(results).sort((a, b) => b[1] - a[1]);
    sorted.forEach(([key, score], index) => {
      const label = names[key] || key;
      const ord = lang === 'en' ? `${index + 1}.` : `${index + 1}º`;
      doc.fontSize(12)
         .fillColor(colors.primary)
         .text(`${ord} ${label}: ${score}%`)
         .moveDown(1);
      const barWidth = (score / 100) * 400;
      const yPos = doc.y;
      doc.rect(doc.x, yPos, 400, 10)
         .fillAndStroke(colors.lightBackground, colors.border);
      doc.rect(doc.x, yPos, barWidth, 10)
         .fill(colors.secondary);
      doc.moveDown(2);
    });
  }
}

function addConclusionPage(doc, userData, tests, colors, roadmap, s, locale = 'en-US') {
  doc.fontSize(24)
     .fillColor(colors.primary)
     .text(s.conclusions, { align: 'center' })
     .moveDown(2);

  addSection(doc, s.summaryOfTests, colors);
  const testsCompleted = Object.keys(tests).length;
  const countText = s.testsCompletedCount.replace('{{count}}', testsCompleted);
  doc.fontSize(11)
     .fillColor(colors.text)
     .text(countText)
     .moveDown(2);

  if (roadmap?.finalMessage) {
    addSection(doc, s.mentorFinalMessage, colors);
    doc.fontSize(11)
       .fillColor(colors.text)
       .text(roadmap.finalMessage, { align: 'justify', lineGap: 4 })
       .moveDown(2);
  }

  addSection(doc, s.nextSteps, colors);
  doc.fontSize(11)
     .fillColor(colors.text)
     .list(s.recommendations, { bulletRadius: 2 })
     .moveDown(2);

  doc.fontSize(10)
     .fillColor(colors.textLight)
     .text(s.reportGeneratedBy, { align: 'center' })
     .moveDown(0.5)
     .text(`${s.generationDate}: ${new Date().toLocaleDateString(locale)}`, { align: 'center' });
}

function addRoadmapSection(doc, roadmap, colors, s) {
  if (!roadmap) return;

  if (roadmap.vision) {
    addSection(doc, s.vision, colors);
    doc.fontSize(11)
       .fillColor(colors.text)
       .text(roadmap.vision, { align: 'justify', lineGap: 4 })
       .moveDown(1.5);
  }

  if (Array.isArray(roadmap.phases) && roadmap.phases.length > 0) {
    addSection(doc, s.developmentPhases, colors);
    roadmap.phases.forEach((phase, index) => {
      const title = phase.title || `${s.phase} ${index + 1}`;
      doc.fontSize(13)
         .fillColor(colors.primary)
         .text(`${index + 1}. ${title}`, { underline: true })
         .moveDown(0.4);
      if (phase.timeframe || phase.focus) {
        const details = [phase.timeframe, phase.focus].filter(Boolean).join(' • ');
        if (details) {
          doc.fontSize(11)
             .fillColor(colors.text)
             .text(details)
             .moveDown(0.6);
        }
      }
      if (Array.isArray(phase.steps) && phase.steps.length > 0) {
        doc.fontSize(11)
           .fillColor(colors.text)
           .list(phase.steps, { bulletRadius: 2 })
           .moveDown(1);
      } else {
        doc.moveDown(0.6);
      }
    });
  }

  if (Array.isArray(roadmap.habits) && roadmap.habits.length > 0) {
    addSection(doc, s.habitsAndSupport, colors);
    doc.fontSize(11)
       .fillColor(colors.text)
       .list(roadmap.habits, { bulletRadius: 2 })
       .moveDown(1.5);
  }

  if (Array.isArray(roadmap.support) && roadmap.support.length > 0) {
    addSection(doc, s.supportNetwork, colors);
    doc.fontSize(11)
       .fillColor(colors.text)
       .list(roadmap.support, { bulletRadius: 2 })
       .moveDown(1.5);
  }
}

/**
 * Adiciona a seção do relatório completo com estrutura de jornada
 */
function addCompleteNarrativeSection(doc, narrative, colors) {
  if (!narrative) return;

  // Processa o markdown e renderiza no PDF
  const lines = narrative.split('\n');
  let currentY = doc.y;

  lines.forEach((line) => {
    // Verifica se precisa de nova página
    if (currentY > doc.page.height - 100) {
      doc.addPage();
      currentY = 60;
    }

    const trimmedLine = line.trim();

    // Títulos (##)
    if (trimmedLine.startsWith('## ')) {
      const title = trimmedLine.substring(3).trim();
      addSection(doc, title, colors);
      currentY = doc.y;
    }
    // Subtítulos (###)
    else if (trimmedLine.startsWith('### ')) {
      const subtitle = trimmedLine.substring(4).trim();
      doc.fontSize(13)
         .fillColor(colors.secondary)
         .text(subtitle, { underline: true })
         .moveDown(0.8);
      currentY = doc.y;
    }
    // Listas com bullets
    else if (trimmedLine.startsWith('- ') || trimmedLine.startsWith('* ')) {
      const item = trimmedLine.substring(2).trim();
      // Remove emojis para o PDF
      const cleanItem = item.replace(/[🧭🎯🚀🌱🔭]/g, '').trim();
      doc.fontSize(11)
         .fillColor(colors.text)
         .text(`• ${cleanItem}`, { indent: 20 })
         .moveDown(0.5);
      currentY = doc.y;
    }
    // Listas numeradas
    else if (/^\d+\.\s/.test(trimmedLine)) {
      const item = trimmedLine.replace(/^\d+\.\s/, '').trim();
      doc.fontSize(11)
         .fillColor(colors.text)
         .text(item, { indent: 20 })
         .moveDown(0.5);
      currentY = doc.y;
    }
    // Texto em negrito (**texto**)
    else if (trimmedLine.includes('**')) {
      const parts = trimmedLine.split(/(\*\*[^*]+\*\*)/g);
      doc.fontSize(11)
         .fillColor(colors.text);
      
      parts.forEach((part) => {
        if (part.startsWith('**') && part.endsWith('**')) {
          const boldText = part.slice(2, -2);
          doc.font('Helvetica-Bold')
             .text(boldText, { continued: true });
        } else if (part.trim()) {
          doc.font('Helvetica')
             .text(part, { continued: true });
        }
      });
      
      doc.moveDown(0.8);
      currentY = doc.y;
    }
    // Parágrafos normais
    else if (trimmedLine && !trimmedLine.startsWith('<') && !trimmedLine.startsWith('</')) {
      // Ignora tags HTML/SVG e linhas vazias
      if (!trimmedLine.match(/^<[^>]+>$/) && trimmedLine.length > 0) {
        // Remove qualquer tag SVG/HTML que possa estar no texto
        const cleanText = trimmedLine.replace(/<[^>]*>/g, '').trim();
        if (cleanText) {
          doc.fontSize(11)
             .fillColor(colors.text)
             .text(cleanText, { align: 'justify', lineGap: 3 })
             .moveDown(0.6);
          currentY = doc.y;
        }
      }
    }
  });
}

